## Vector arithmetic

In [1]:
import numpy as np

In [2]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

In [3]:
a+b

array([30, 60, 90])

In [4]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [5]:
a-b

array([10, 20, 30])

In [6]:
a-c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [7]:
multi=a*b
print(multi)

[ 200  800 1800]


In [8]:
div=a/b
print(div)

[2. 2. 2.]


In [9]:
scalar=5

In [10]:
list_a=[10,11, 12, 13, 14, 15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [11]:
list_as_array=np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


In [12]:
scalar*list_a

[10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15,
 10,
 11,
 12,
 13,
 14,
 15]

In [13]:
scalar*list_as_array

array([50, 55, 60, 65, 70, 75])

## Dot product of vectors

In [14]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [15]:
np.dot(a,b)

130

In [16]:
c =np.array([11,12,13,14,15])

In [17]:
np.dot(b,a)

130

In [18]:
first_result=np.dot(a,b+c)
print(first_result)

335


In [19]:
second_result=np.dot(a,b)+np.dot(a,c)
print(second_result)

335


In [20]:
np.dot(b,a)

130

## Scalar and vector projection

In [21]:
from numpy import linalg as lng

In [22]:
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])

In [23]:
len_a=lng.norm(a)

In [24]:
vector_projection=(np.dot(a,b)/np.dot(b,b))*b
print(vector_projection)

[23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]


## Gaussian elimination and finding the inverse matrix

In [26]:
A= np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [27]:
Ainv=np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
b=np.array([5,11])
b

array([ 5, 11])

In [29]:
x=np.dot(Ainv,b)
x

array([1., 2.])

In [30]:
np.dot(A,x)

array([ 5., 11.])

## Inverse and determinant

In [31]:
A= np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [32]:
det=np.linalg.det(A)
det

-2.0000000000000004

In [33]:
B= np.array([[3,1],[6,2]])
B

array([[3, 1],
       [6, 2]])

In [34]:
np.linalg.det(B)

0.0

In [35]:
np.linalg.inv(B)

LinAlgError: Singular matrix